name: diag
on:
  workflow_dispatch:
  push:
    paths: [".github/workflows/diag.yml"]

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (internal)
        env:
          TOKEN: ${{ github.token }}
        run: |
          set -euxo pipefail
          rm -rf repo
          git clone --depth=1 "https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git" repo
          cd repo
          git rev-parse --abbrev-ref HEAD
          echo "WORKDIR=$PWD" >> $GITHUB_ENV
          ls -la

      - name: Python presence
        run: |
          set -euxo pipefail
          python3 --version
          python3 -m pip --version || true

      - name: Install deps (fail fast when requirements.txt is missing)
        run: |
          set -euxo pipefail
          cd "$WORKDIR"
          test -f requirements.txt || (echo "requirements.txt missing"; exit 2)
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Sanity checks (files exist)
        run: |
          set -euxo pipefail
          cd "$WORKDIR"
          test -f scripts/run_digest_job.py || (echo "missing scripts/run_digest_job.py"; exit 3)
          test -d src || (echo "missing src/"; exit 4)
          echo "diag done"

