name: crypto-digest
on:
  schedule:
    - cron: "0 */6 * * *"      # 6時間ごと
  workflow_dispatch:

concurrency:
  group: crypto-digest
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt

      - name: Run digest job
        env:
          # Telegram
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_STRING_SESSION: ${{ secrets.TG_STRING_SESSION }}
          SOURCE_CHATS: "kudasai_jp"    # カンマ区切りで複数可

          # Gemini
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GEMINI_MODEL: "models/gemini-2.0-flash"

          # Discord
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

          # 窓
          HOURS_24: "24"
          HOURS_RECENT: "6"

          # ログ
          QUIET_LOG: "1"
        run: python scripts/run_digest_job.py

      - name: Upload state
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: state
          path: state/
          if-no-files-found: ignore
          retention-days: 7
