name: ai-matome
on:
  schedule:
    - cron: "0 */6 * * *"   # 6時間ごと
  workflow_dispatch:

concurrency:
  group: ai-matome
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write   # artifact に state.json を保存するため
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run matome job
        env:
          # Telegram
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_STRING_SESSION: ${{ secrets.TG_STRING_SESSION }}
          SOURCE_CHATS: "kudasai_jp"     # 監視対象（カンマ区切り可）

          # Gemini
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GEMINI_MODEL: "models/gemini-2.0-flash"  # 好みで

          # Discord
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

          # 窓
          HOURS_24: "24"
          HOURS_RECENT: "6"

          # ログ方針
          QUIET_LOG: "1"

        run: python scripts/run_matome_job.py

      - name: Upload state
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: state
          path: state/
          if-no-files-found: ignore
          retention-days: 7
